import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Inter } from 'next/font/google';

const myFont = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable:"--my-font-family",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        // className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-fixed bg-cover bg-center bg-no-repeat`}
        // className={`${myFont.className}antialiased min-h-screen bg-fixed bg-cover bg-center bg-no-repeat`}
        className={`${myFont.className} antialiased min-h-screen bg-fixed bg-cover bg-center bg-no-repeat`}
        style={{
          backgroundImage: "url('/Chargebee.jpg')", // Replace with your image path
          // backgroundColor: "rgba(0, 0, 0, 0)", // Optional: adds a dark overlay
          // backgroundBlendMode: ""
        }}
      >
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem 
          disableTransitionOnChange
        >
          <EdgeStoreProvider>
            {/* Optional semi-transparent overlay */}
            <div className="min-h-screen bg-black/30"> 
              <Navbar/>
              {children}
            </div>
          </EdgeStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
